name: glass_toast_flutter
description: A Flutter package for displaying beautiful glass-morphism toast notifications with blur effect and smooth animations.
version: 0.0.1
repository: https://github.com/harshjaiswalcis/glass_toast_flutter
homepage: https://github.com/harshjaiswalcis/glass_toast_flutter

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
