name: transparent_mirror_toast
description: A customizable Flutter toast widget with a sleek transparent and mirror-glass effect.
version: 1.0.0
homepage: https://github.com/yourusername/transparent_mirror_toast
repository: https://github.com/yourusername/transparent_mirror_toast

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
